#Universe parameters
NUM_CYCLES = 500
STEPS_PER_CYCLE = 100

GRID_SIZE_X = 1600
GRID_SIZE_Y = 900

NEST_RADIUS = 5.0
WATER_SOURCES_RADIUS = 10.0

# Caracteristics of cell parameters: Cost of being alive and moving
CELL_METABOLISM_BASE = 0.020
STEP_SIZE = 1.0                  # Distance moved per step
REPRO_ENERGY_THRESHOLD = 30.0
VELOCITY_COST_FACTOR = 0.020
THIRST_PENALTY = 0.020
HYDRATION_COST_FACTOR = 0.012

ACCELERATION = 0.30
MAX_SPEED = 1.4
DAMPING = 0.90
NOISE_RW = 0.08

ALMOST_ZERO = 1e-9



# Iteraction with universe parameters
FOOD_VALUE = 10.0
INITIAL_ENERGY = 20.0
INITIAL_POPULATION = 20
INITIAL_HYDRATION = 10.0

THIRST_THRESHOLD = 6
HUNGRY_TRESHOLD = 10

EATING_THRESHOLD = 1
DRINKING_THRESHOLD = 2.3

HYDRATION_LIMIT = 20
ENERGY_LIMIT = None


# Reproduction
CHILD_PART = 0.45
PARENT_PART = 1 - CHILD_PART
COOLDOWN = 220